name             'wkhtmltox'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wkhtmltox'
long_description 'Installs/Configures wkhtmltox'
version          '0.1.2'

depends 'chef-sugar', '~> 2.5.0'
depends 'gdebi',      '~> 1.1.0'
depends 'apt',        '~> 2.7.0'
