name             'wkhtmltox'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wkhtmltox'
long_description 'Installs/Configures wkhtmltox'
version          '0.1.0'

depends 'chef-sugar'
depends 'gdebi'
depends 'apt'
